version: "3"

services:
  backend-service:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000

  frontend-service:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    depends_on:
      - backend-service
