on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "Start flask backend"
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          curl --create-dirs -o $HOME/.postgresql/root.crt -O https://cockroachlabs.cloud/clusters/85831b76-682e-41ba-8ecd-9956fe67b9b1/cert
          pip install -r requirements.txt
          python app.py &

      - name: "Start frontend"
        working-directory: frontend
        env:
          NEXT_PUBLIC_API_URL: http://localhost:5000/
          NEXT_PUBLIC_API_QR: https://api.qrserver.com/v1/create-qr-code/
          NEXT_PUBLIC_URL: http://localhost:3000
        run: |
          npm install
          npm run build
          npm run start &
